version: '2'
services:
  grafana:
   image: grafana/grafana
   links:
    - influx:influx
   ports:
    - 3000:3000
   environment:
    - GF_SERVER_ROOT_URL=http://grafana.server.name
    - GF_SECURITY_ADMIN_PASSWORD=secret
   volumes:
    - ./grafana:/var/lib/grafana
   depends_on:
     - busybox
  influx:
   image: influxdb
   volumes:
    - ./conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    - influx-storage:/var/lib/influxdb
   command: -config /etc/influxdb/influxdb.conf
  busybox:
   image: busybox
   volumes:
    - ./grafana:/var/lib/grafana

volumes:
  influx-storage:
